
[config]
schemaVersion = "0.0.1"

[package]
namespace = "RiskofThunder"
name = "R2API_CostType"
versionNumber = "1.0.0"
description = "API for creating custom cost types."
websiteUrl = "https://github.com/risk-of-thunder/R2API"
containsNsfwContent = false

[package.dependencies]
bbepis-BepInExPack = "5.4.2109"
RiskofThunder-HookGenPatcher = "1.2.3"
RiskofThunder-R2API_Core = "1.0.0"

[build]
icon = "../icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./ReleaseOutput/R2API.CostType.dll"
target = "./plugins/R2API.CostType/R2API.CostType.dll"

[[build.copy]]
source = "./ReleaseOutput/R2API.CostType.xml"
target = "./plugins/R2API.CostType/R2API.CostType.xml"

[publish]
repository = "https://thunderstore.io"
communities = ["riskofrain2"]
categories = ["libraries"]
